### ISSUE TITLE
Literal String Instead of List of Lists in Template_Params Causes Unexpected Behavior in CustomDataset Constructor

### ISSUE THREAD

**Issue by hugocool** [takikadiri/kedro-boot#6]
We are experiencing an issue where the literal string `'[[ data_ids ]]'` is being passed to the constructor of our dataset, instead of the expected list of lists. This problem occurs in the context of a FastAPI route with a Kedro session and a custom dataset configuration using a catalog entry.

Here are the details of the issue and our current workaround:

1. **FastAPI Route with Kedro Session:**

   In our FastAPI application, we have a route that uses a Kedro session to run a task. The `data_ids` parameter, which is intended to be a list of integers, is being incorrectly passed as a string. Here's the relevant part of the route:

   ```python
   # ... [previous code for route setup] ...

   @app.post("/api/v1/data", response_model=OutputData)
   async def get_output_data(input_data: InputData):
       data_ids = input_data.data_ids  # data_ids is expected to be a list of ints

       # ... [additional code and logging] ...

       output = session.run(
           name="web_api", 
           inputs={"input_data": input_data},
           template_params={"data_ids": data_ids},
       )
   ```

2. **Catalog Entry Issue and Workaround:**

   The issue also manifests in our catalog entry configuration for a custom dataset:

   ```yaml
   result:
     type: performance_optimisation_engine.extras.datasets.web_api_dataset.ResultDataset
     credentials: mysql
     data_ids: [[ data_ids ]]
   ```

   With this setup, the string `'[[ data_ids ]]'` is passed to the constructor instead of the list of lists. To address this, we modified the catalog entry to pass `data_ids` as a string explicitly:

   ```yaml
   result:
     type: performance_optimisation_engine.extras.datasets.web_api_dataset.ResultDataset
     credentials: mysql
     data_ids: '[[ data_ids ]]'
   ```

   Then, in the constructor of our dataset, we convert this string back into a list of lists:

   ```python
   s = str(self.data_ids).replace("'", '"')
   self.data_ids = json.loads(s)
   ```

While this workaround is functional, it's not ideal. We suspect this might be a bug or at least a feature that requires clarification in the documentation. Any assistance in resolving this issue more elegantly would be greatly appreciated.

Thank you for your time and consideration.
